# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "japan-geoid"
version = "0.1.0"
edition = "2021"
authors = ["Taku Fukada <naninunenor@gmail.com>", "MIERUNE Inc. <info@mierune.co.jp>"]

[dev-dependencies]
flate2 = "1.0.27"
lz4_flex = "0.11.1"
zstd = "0.13.0"

[workspace]
resolver = "2"
members = ["./japan-geoid-py"]

[profile.dev.package."*"]
opt-level = 1
